import { ExampleComponent } from "@/components/example-component";
import { TamboProvider } from "@tambo-ai/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tamboComponents = [
  {
    name: "ExampleComponent",
    description: "A product card component that displays product information with customizable pricing, discounts, and styling. Perfect for demonstrating interactive UI elements!", // Here we tell tambo what the component is for and when to use it
    component: ExampleComponent, // Reference to the actual component definition
    propsDefinition: {
      productName: "string",
      price: "number",
      description: "string",
      discountPercentage: "number",
      accentColor: {
        type: "enum",
        options: ["indigo", "emerald", "rose", "amber"]
      },
      inStock: "boolean"
    } // Here we tell tambo what props the component expects
  },
  // Add more components for Tambo to control here!
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TamboProvider
          apiKey={process.env.NEXT_PUBLIC_TAMBO_API_KEY!}
          components={tamboComponents}
        >
          {children}
        </TamboProvider>
      </body>
    </html>
  );
}
